stages:
  - build
  - deploy

build:
  stage: build
  # remember to use specific version in your build images
  # see https://blog.callr.tech/building-docker-images-with-gitlab-ci-best-practices/
  image: docker:18-git 
  # we only build the "master" branch
  only:
    - master
  # fetching submodules here because usually themes are git submodules
  # see also the commented variables below

  before_script:
    - docker info

  script:
    - echo -n $SAGITAL_REGISTRY_PASSWORD | docker login -u $SAGITAL_REGISTRY_USER --password-stdin $CI_REGISTRY
    # the image is tagged as latest, because it is the master branch
    - docker build -t $CI_REGISTRY/sagital/hugo-site:latest .
    - docker push $CI_REGISTRY/sagital/hugo_site:latest
  # variables:
  #   GIT_SUBMODULE_STRATEGY: recursive
  # -> this did not work for us, we had to use before_script above.
  # -> SSL certificate problem: unable to get local issuer certificate
  # -> https://gitlab.com/gitlab-org/gitlab-runner/issues/2148?
  # -> maybe an http proxy issue specific to our platform.

